### ISSUE TITLE
插件不工作

### ISSUE THREAD

**Issue by Eyion** [imfenghuang/obsidian-immersive-translate#3]
1. 点击悬浮窗（选中或不选中文字），结果没有进行翻译；
2. 打开“鼠标悬停:+Ctrl 翻译/还原该段”，鼠标悬停在某段文字并按下Ctrl键，结果没有进行翻译。

**Comment by imfenghuang** [comment]
hi @Eyion 请问是在哪个模式下，阅读模式？还是源码模式？

**Comment by Eyion** [comment]
@imfenghuang 切换到阅读视图就正常翻译了。编辑视图不支持对吗？所以对翻译结果也无法进行修正？

**Comment by imfenghuang** [comment]
> @imfenghuang 切换到阅读视图就正常翻译了。编辑视图不支持对吗？所以对翻译结果也无法进行修正？

目前插件工作在阅读模式下，编辑模式我需要再看看怎样支持。

**Comment by Eyion** [comment]
好的，谢谢。
